import { Theme } from "../interfaces/interface";

const PrimaryTheme: Theme = {
  primary: '#974578',
  appBar: '#121212',
  variant: '#c973a7',
  textPrimary: '#713779',
  dark: '#747474',
  light: '#f7f7f7',
  transparent: 'transparent',
  transparentSurface: 'rgb(255 255 255 / 85%)',
  icon: '#282828',
  info: '#0095ff',
  purple: '#673AB7',
  success: '#28a745',
  white: '#ffffff',
  background: '#f7f7f7',
  warn: '#ffb400',
  black: '#282828',
  active: '#974578',
  danger: '#ff3d71',
  text: '#282828',
  surface: '#06014a',
  secondary: '#b79cff',
  onBackground: '#000',
  onSurface: '#000',
  onPrimary: '#fff',
  borderColor: '#f0f3f5',
  google: '#ea4335',
  facebook: '#1877f2',
  apple: '#282828',
  onSecondary: '#000',
  rating: '#ffb400',
  fonts: {
    Roboto: 'Roboto',
    RobotoMedium: 'RobotoMedium',
    ProductSansRegular: 'ProductSansRegular',
    ProductSansLight: 'ProductSansLight',
    ProductSansBold: 'ProductSansBold',
    ProductSansMedium: 'ProductSansMedium',
    LemonadaMedium: 'LemonadaMedium',
    LemonadaBold: 'LemonadaBold',
    LemonadaLight: 'LemonadaLight',
    LemonadaSemiBold: 'LemonadaSemiBold',
    LemonadaRegular: 'LemonadaRegular',
    RubikRegular: "RubikRegular",
    RubikMedium: "RubikMedium",
    RubikLight: "RubikLight",
    RubikItalic: "RubikItalic",
    RubikBold: "RubikBold",
    primaryFont: "PrimaryFont",
    boldFont: 'BoldFont',
    lightFont: 'LightFont',
    mediumFont: 'MediumFont'
  },
  fontSizes: {
    heading: 36,
    title: 26,
    body: 18,
    subtitle: 20,
    small: 16
  }
}

export default PrimaryTheme;